site_name: Larahorse
nav:
  - Home: index.md
  - Larahorse: larahorse.md
  - Technischer Aufbau: technischeraufbau.md
  - So tut man es: sotutmanes.md

  - ---------------------------------: dummy.md

  - Planing: _planning.md

theme: readthedocs

